import './components/ship.js';
import './components/controls.js';
import './components/city-generator.js';
import './components/infinite-ocean.js';
import './components/starry-sky.js';
import './components/enemy-ship.js';
import './components/cockpit-compass.js';
import './components/retro-sfx.js';
import './scenes/futuristic-city-scene.js';